---
title: "Midterm practice (2024)"
format: 
  pdf:
    include-in-header:
      text: '\pagenumbering{gobble}'
author: "Name: _______________________"
---

**Question 1: `R` code interpretation**

Consider this `R` code.

```{r}
#| eval: true
gender <- c("male", "female", "female", "male", "female")
educ <- c(rep("HS", 3), "college", "college")
earnings <- c(1, 0, 2, 8, 4)
```

(1a) What is `mean(earnings)`? 


\vspace{1in}

(1b) What is `mean(earnings[gender == "female"])`?


\vspace{1in}

(1c) What is `mean(earnings[gender == "female" & educ == "HS"])`?


\vspace{1in}

(1d) What is `mean(earnings[earnings <= 4])`?


\vspace{2in}


**Question 2: Proof interpretation**

*Theorem:* If events $A$ and $B$ are independent and $P(B) > 0$, then $P(A \mid B) = P(A)$.

*Proof:* 

\begin{align}
P(A \cap B) &= P(A)P(B)  \tag{Step 1}\\
P(A \mid B) P(B) &= P(A) P(B)  \tag{Step 2}\\ 
P(A \mid B) &= P(A)  \tag{Step 3} 
\end{align}

Explain what definition/property/mathematical operation is being used in each step of the proof.

(2a) Step 1: 

\vspace{1in}

(2b) Step 2:

\vspace{1in}

(2c) Step 3:

\vspace{1in}

(2d) Explain in words what $P(A \mid B) = P(A)$ means.

\vspace{2in}



**Question 3: Joint distribution of two random variables**

Consider the joint PMF of two random variables, $X$ and $Y$:

| $x$   | $y$ | $f(x, y)$    |
|:-----:|:-----:|:----------:|
|   0   |   0    |    1/4    |
|   0   |   1    |    1/5    |
|   1   |   0    |    1/5    |
|   1   |    1   |   1/10     |
|   1   |    2   |   1/4     |


(3a) What is the marginal distribution of $X$, i.e. $f_X(x)$?

| $x$   | $f_{X}(x)$  |
|:-----:|:-----:|
|   0   |       |       
|   1   |       | 

(3b) What is the expectation of $X$, i.e. $E[X]$? 

\vspace{1in}

(3c) What is the standard deviation of $X$, i.e. $\sigma[X]$? 



\vspace{1in}

(3d) What is the conditional distribution of $Y$ given $X$, i.e. $f_{Y\mid X}(y \mid x)$?  


| $x$   | $y$ | $f_{Y\mid X}(y \mid x)$  |
|:-----:|:-----:|:----------:|
|   0   |   0    |        |
|   0  |   1    |         |
|   1   |   0    |         |
|   1    |    1   |          |
|   1    |    2   |          |


